//UI PAGE
export const TOGGLE_IS_LOADING = "UIPage/TOGGLE_IS_LOADING";
export const SET_ERROR = "UIPage/SET_ERROR";
export const CLEAR_ERROR = "UIPage/CLEAR_ERROR";
export const TOGGLE_IS_WAIT_GET_STRIP = "UIPage/TOGGLE_IS_WAIT_GET_STRIP";
export const TOGGLE_IS_SHOW_BACKDROP = "UIPage/TOGGLE_IS_SHOW_BACKDROP";
export const OPEN_SIDE_DRAWER = "UIPage/OPEN_SIDE_DRAWER";
export const TOGGLE_IS_SHOW_SIDE_DRAWER = "UIPage/TOGGLE_IS_SHOW_SIDE_DRAWER";
export const TOGGLE_IS_WAIT_SORT = "UIPage/TOGGLE_IS_WAIT_SORT";

//STRIPS PAGE
export const SET_STRIPS = "stripsPage/SET_STRIPS";
export const SET_STRIP = "stripsPage/SET_STRIP";

//BAG PAGE
export const ADD_TO_BAG_PRODUCT = "bagPage/ADD_TO_BAG_PRODUCT"
export const GET_PRODUCTS_FROM_LS = "bagPage/GET_PRODUCTS_FROM_LS"
export const INCREASED_METERS_AND_PRICE = "bagPage/INCREASED_METERS_AND_PRICE"
export const DECREASED_METERS_AND_PRICE = "bagPage/DECREASED_METERS_AND_PRICE"
export const DELETE_ELEMENT_FROM_BAG = "bagPage/DELETE_ELEMENT_FROM_BAG"